server:
  port: 8787
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  mvc: 
    view:
      prefix: /WEB-INF/views/   # controller 리턴값 앞에 붙여주는 RESTController x
      suffix: .jsp              # controller 리턴값 뒤에 붙여주는
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: seek
    password: seek7235
  security:
    user:
      password: 7235
  
  jpa:
    open-in-view: true # lazy전략을 사용할 수 있게 한다. controller까지 영속성컨텍스트를 열어두는 전략
    hibernate:
      ddl-auto: update   # create : 실행할때마다 테이블 생성 / 나중에는 업데이트로 바꿔야함
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #변수명 그대로 테이블에 이름 삽입전략
      use-new-id-generator-mappings: false #jpa가 사용하는 기본 넘버링을 따라가지않는다.
    show-sql: true  # 콘솔창에 sql 보여줌
    properties:
      hibernate.format_sql: true  # 콘솔에 sql 찍을때 줄바꿈해줌
  jackson:
    serialization:
      fail-on-empty-beans: false
